# Generated by Django 5.2.1 on 2025-05-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.CharField(max_length=3),
        ),
    ]
