# Generated by Django 5.2.1 on 2025-05-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_alter_ticket_seat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
                ),
                (
                    "distance_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.1,
                        help_text="Price per km of distance",
                        max_digits=5,
                    ),
                ),
                (
                    "airplane_type_premium",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Multiplier for premium airplane types",
                        max_digits=5,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ticket",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
