# Generated by Django 5.2.1 on 2025-05-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_price_ticket_price"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Price",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="price",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.CharField(max_length=1),
        ),
    ]
